### PR TITLE
fix: didn't hide infospot when change panorama

### PR DESCRIPTION
**Pull request by xuanvan229**
Hi. I got some bugs. When changing PanoramaImage. Some infospot didn't hide the text. I have fixed it. Please take a look.

### CODE REVIEW

**Comment by claytonrothschild** [comment]
Nice. This was a pain point for me, which I solved with an agressive dispose method on scene change. 

```
this.viewer.panorama && this.viewer.panorama.children && this.viewer.panorama.children.map(c => { c.removeHoverElement && c.removeHoverElement(); c.hide(); c.dispose(); });
```

Your solution is better.

**Comment by flyandi** [comment]
Can we merge this please since so many have issues with this?

**Comment by RamenKebab** [comment]
Hi @claytonrothschild! I used your solution in my panorama changing function, it worked and hid the hoverText in the new panorama. However, it doesn't work for the popups (a div with a texte on white background) that comes when hovering an infoSpot..

function onButtonClick( targetPanorama ) {
  bar.classList.remove( 'hide' );
  **this.viewer.panorama && this.viewer.panorama.children && this.viewer.panorama.children.map(c => { c.removeHoverElement && c.removeHoverElement(); c.hide(); c.dispose(); });**
viewer.setPanorama( targetPanorama ); 
}
...........
infospotHS.addHoverElement( document.getElementById( 'popup' ), 270 );

I am a beginner, I didn't get @xuanvan229's solution as I am not at all using infospot.js :/

Thank you.

**Comment by RamenKebab** [comment]
actually how can i use infospot.js while i'm using panolens.min.js ? For custom infospot, it seems necessary. Thanks

**Comment by xuanvan229** [comment]
Hi @RamenKebab,  infopost.js has built to panolens.min.js. So If you want to use it in your project. You should change it in your panolens.min.js file or panolens.js

You can find it here.
https://github.com/pchen66/panolens.js/blob/master/build/panolens.js#L2498

**Comment by RamenKebab** [comment]
@xuanvan229 This is divine. Your fix works like a charm. Thanks for guidance.

**Comment by RamenKebab** [comment]
@xuanvan229 However, it does not work in the Cardboard Mode. These stubborn hoverTexts still don't dissappear...

**Comment by flyandi** [comment]
I am merging this as this has been a real pain point.

**Comment by claytonrothschild** [comment]
Welcome @flyandi glad to have a active maintainer on the project again!

**Pull request merged**
