### PR TITLE
Added type definitions

### PR DESCRIPTION
**Pull request by giordanocardillo**

### CODE REVIEW

**Comment by flyandi** [comment]
Can you describe a little bit more your intention of this MR please. I am not sure if I follow. I just took over this project so just catching up.

**Comment by predorock** [comment]
@flyandi will be very useful to use thi lib with Typescript. The PR aims to add them.

**Comment by giordanocardillo** [comment]
I’m sorry, didn’t see the mail. I’ve made the type definitions for this awesome library to make it easier to use with typescript. I’ve used it in a personal project and I thought it could be useful that this could be included

**Comment by flyandi** [comment]
Oh wow - very cool. One thing that comes into my mind: When we add / change / update - can these files be auto regenerated or is that something that needs to be handed manually. Sorry I am not really into TS.

**Comment by giordanocardillo** [comment]
It must be updated by hand accordingly

**Comment by predorock** [comment]
Well type defs can be generated from .js lib but of course tests will be necessary. 

From stackoverflow: https://stackoverflow.com/questions/12687779/how-do-you-produce-a-d-ts-typings-definition-file-from-an-existing-javascript

Typedefs generation lib: https://github.com/Microsoft/dts-gen

This PR is a good point of start and I think that types will not change that often so modify them by hand can be a not so hard job..

**Comment by flyandi** [comment]
I am merging this.

**Pull request merged**
