### PR TITLE
Fix panorama error event

### PR DESCRIPTION
**Pull request by blaspix-tech**
Hello @pchen66 ,

Currently the error event isn't dispatch during the ajax request.
I don't know if my fix cover all the cases but it works as expected now.

### CODE REVIEW

**Comment by flyandi** [comment]
you should expose the onreadystatechange on an event rather than re-using onEnter. Also the way u have it right now will break if onError is null as the addeventlistener will do the check for you. I like the idea to expose the onreadystatechange but should be more generic.

**Comment by bierdok** [comment]
the event listener doesn't trigger the fact that the URL is wrong, what do you propose then?

**Comment by flyandi** [comment]
Yeah I see your point. If we just want to serve the `onError` event - this is the way to go.

**Comment by flyandi** [comment]
I am re-running the travis CI job to get it merged in.

**Comment by flyandi** [comment]
I have no idea why the build is failing but I will add your stuff manually into the latest version and close this issue. Will be available in 0.12.1

**Pull request closed without merging**
